name: Build

on: [push, pull_request]

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        make ERRORS=Y liblunar.a
        make install
        cd ..
        make
        make cgiradar jpl2ast jpl2sof radar getradar

  buildOSX:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        make CLANG=Y ERRORS=Y liblunar.a
        make install
        cd ..
        echo > clock1
        make CLANG=Y
        make CLANG=Y cgiradar jpl2ast jpl2sof radar getradar

